# Generated by Django 5.0.2 on 2024-03-13 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_pubdate_alter_post_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pubDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 11, 53, 48, 133686, tzinfo=datetime.timezone.utc), verbose_name='published_date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='pubDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 11, 53, 48, 133235, tzinfo=datetime.timezone.utc), verbose_name='published_date'),
        ),
    ]
