# Generated by Django 5.0.2 on 2024-03-17 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_comment_pubdate_alter_post_pubdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="pubDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 17, 10, 28, 17, 416449, tzinfo=datetime.timezone.utc
                ),
                verbose_name="published_date",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="pubDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 17, 10, 28, 17, 415968, tzinfo=datetime.timezone.utc
                ),
                verbose_name="published_date",
            ),
        ),
    ]
